### ISSUE TITLE
all/backend_issues_demo

### ISSUE THREAD

**Issue by Jess-jpg-txt** [jadham2/MakeMyDegree#16]
* still need to create endpoints for tags
* still need to create endpoints for requisite
* endpoints for course in the work
* use an actual degree plan for demo, insert CompE degree into DB

**Comment by jadham2** [comment]
Also need to complete validation for degree plan (if we decide to try and do for demo)

**Comment by jadham2** [comment]
resolving this. we finished all besides validation (will make new issue).
